name: Test-Step1

on:
  push:
    branches:
      - main
      - dev

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello world
        shell: bash
        run: echo Welcome to the Github Actions workshop !
